const allPagesRoutes = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  CONTACT_US: "/contact",
  ABOUT_US: "/about-us",
  USER_PROFILE: "/user/my-profile",
  MY_ORDERS: "/user/my-orders",
  MY_WISHLIST: "/user/my-wishlist",
  CHANGE_PASSWORD: "/user/change-password",
  PRIVACY_POLICY: "/privacy-policy",
  FAQS: "faqs",
  TERMS_AND_CONDITION: "terms-and-conditions",
  BUSINESS_IT_SUPPORT: "business-it-support",
  CLOUD_STORAGE_AND_BACKUP: "/Cloud-Storage-And-Backup",
  EMAIL_SUPPORT_AND_BACKUP: "/Email-Support-And-Backup",
  computer_repairs: "/Computer-Repairs",
  tablet_repairs: "/Tablet-Repairs",
  Macbook_repairs: "/macbook-repairs",
  Laptop_Repairs_Sydney: "/Laptop-Repairs-Sydney",
  Mobile_Repairs: "/Mobile-Repairs",
  PRODUCTS: "/products",
  PRODUCT_DETAILS: "/products/product-details",
  CART: "/cart",
  BRANDS: "/brands",
};

export default allPagesRoutes;
