const allPagesRoutes = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  CONTACT_US: "/contact",
  ABOUT_US: "/about-us",
  USER_PROFILE: "/user/my-profile",
  MY_ORDERS: "/user/my-orders",
  MY_WISHLIST: "/user/my-wishlist",
  CHANGE_PASSWORD: "/user/change-password",
  PRIVACY_POLICY: "/privacy-policy",
  FAQS: "/faqs",
  TERMS_AND_CONDITION: "/terms-and-conditions",
  BUSINESS_IT_SUPPORT: "/services/business-it-support",
  CLOUD_STORAGE_AND_BACKUP: "/services/cloud-storage-and-backup",
  EMAIL_SUPPORT_AND_BACKUP: "/services/email-support-and-backup",
  computer_repairs: "/services/computer-repairs",
  tablet_repairs: "/services/tablet-repairs",
  Macbook_repairs: "/services/macbook-repairs",
  Laptop_Repairs_Sydney: "/services/laptop-repairs-sydney",
  Mobile_Repairs: "/services/mobile-repairs",
  PRODUCTS: "/products",
  PRODUCT_DETAILS: "/products/product-details",
  CART: "/cart",
  BRANDS: "/brands",
};

export default allPagesRoutes;
